#!/bin/sh

lb clean noauto ${@}

# Remove empty directories in config tree
if ls config/*/ > /dev/null 2>&1
then
	rmdir --ignore-fail-on-non-empty config/*/
fi

if [ -d config ]
then
	rmdir --ignore-fail-on-non-empty config
fi
